### ISSUE TITLE
Why Scene (Action-Set) added to Home(HMHome) always have updated Characteristic's(HMCharacteristic) values :HomeKit

### ISSUE THREAD

**Issue by kamarshad** [KhaosT/HomeKit-Demo#21]
Hello KhaosT,

I am working on a Demo iOS application based on HomeKit API's.
I am facing a problem in updating Scene(ActionSet), looking for your help.

Here is the complete details of that problem,Please take a look.
https://discussions.apple.com/message/27487922#27487922

Thanks.

**Comment by KhaosT** [comment]
I'm sorry but after reading your post three times, I still don't understand what's the problem… The target value of write action should remain separated from the actual characteristic. Can you use a different way to describe the problem?

**Comment by kamarshad** [comment]
Sorry for that.

I have also posted my problem here http://stackoverflow.com/questions/27982281/why-sceneaction-set-added-to-homehmhome-always-have-updated-characteristics

Please take a look

**Comment by KhaosT** [comment]
@kamarshad I added the ability to rename action sets in commit 7e249d51f but I was not able to reproduce your issue. HMCharacteristicWriteAction's target value remains the same.
