### ISSUE TITLE
Triggers and Action Sets

### ISSUE THREAD

**Issue by lukingtn** [KhaosT/HomeKit-Demo#22]
Does the Triggers and Action Sets portion of this application work? I'm not sure if Im doing something wrong or that section is not complete. 

When I try and add an action set it lets me name it, but when I go into the action set I am not able to add any actions, the option to execute my empty action set leads me to believe there is someway to get the create actions within the action set but its not clear how.

**Comment by KhaosT** [comment]
@lukingtn Sorry for the confusion. This part if fully functional but the way to setup action is a little bit tricky.
To add action to an action set, you'll need to go to the accessory you want to change, swipe left on the characteristic cell that you need change and there is a button to create action and assign it to action set.
