### ISSUE TITLE
Siri doesnt respond to Room request

### ISSUE THREAD

**Issue by michaelrcarroll** [KhaosT/HomeKit-Demo#24]
Per https://developer.apple.com/library/ios/documentation/HomeKit/Reference/HomeKit_Framework/, Apple says that we should be able to say: “Siri, turn on the kitchen lights.”

I've added two lights to a "Living Room" Room, which work on their own when I ask the generic "Siri, turn on the lights". When I ask to turn on the living room lights, Siri times out and says I can't help you right now.

Any ideas what could be causing this, or is it something on iOS that isn't quite ready yet?

**Comment by KhaosT** [comment]
@michaelrcarroll It seems that feature is experiencing a server side issue since December. If you have time, please try to also file a bug at [Apple's bug report system](https://bugreport.apple.com) thanks :)
