### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by micpura** [KhaosT/HomeKit-Demo#25]
I get the following error and have no clue how to resolve it...

target specifies product type 'com.apple.product-type.application.watchapp', but there's no such product type for the 'iphoneos' platform

any idea would be appreciated.

**Comment by KhaosT** [comment]
@micpura Please use Xcode 6.3b2 to compile the project. If you just need a HomeKit app, you can try [this one](https://developer.apple.com/library/prerelease/ios/samplecode/HomeKitCatalog/Introduction/Intro.html#//apple_ref/doc/uid/TP40015048)

**Comment by micpura** [comment]
I did install that app just fine. But it never detected an accessory... 
I'm on same IP network.
Node Core.js starts fine

Any idea?

**Comment by KhaosT** [comment]
@micpura can you take a look at [this issue](https://github.com/KhaosT/HAP-NodeJS/issues/42)?

**Comment by micpura** [comment]
Thanks. Tried that with no luck.  I ran through all the steps again and it seems like node-gyp never got installed.  Don't know I got it to rebuild in the first place...

I get a trace/break error trying to install node-gyp now.  Should I specify a version to install?

**Comment by micpura** [comment]
got it to install via, npm explore npm -g -- npm install node-gyp@latest
install v 1.0.2
when i run npm rebuild in HAP-NodeJS
I get error  curve25519@1.0.0 install: node-gyp rebuild

**Comment by micpura** [comment]
root@raspberrypi:/home/pi/HAP-NodeJS# npm rebuild

> curve25519@1.0.0 install /home/pi/HAP-NodeJS/node_modules/curve25519
> node-gyp rebuild

gyp ERR! clean error
gyp ERR! stack Error: EACCES, unlink 'build'
gyp ERR! System Linux 3.18.7-v7+
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/pi/HAP-NodeJS/node_modules/curve25519
gyp ERR! node -v v0.10.35
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok

npm ERR! curve25519@1.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the curve25519@1.0.0 install script.
npm ERR! This is most likely a problem with the curve25519 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls curve25519
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.18.7-v7+
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "rebuild"
npm ERR! cwd /home/pi/HAP-NodeJS
npm ERR! node -v v0.10.35
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/HAP-NodeJS/npm-debug.log
npm ERR! not ok code 0

**Comment by KhaosT** [comment]
@micpura Are you sure you have "build-essential" installed on your Raspberry Pi?

**Comment by micpura** [comment]
I installed the recommend Raspian debian build...

**Comment by KhaosT** [comment]
@micpura I'm not sure then... there is nothing special in the error log.

**Comment by micpura** [comment]
Im going to start over from scratch...

follow these steps...

Install Raspian recommended..
apt-get update
apt-get install git-core libnss-mdns libavahi-compat-libdnssd-dev -y
(changed to old version)
wget http://node-arm.herokuapp.com/node_0.10.35_armhf.deb
dpkg -i node_0.10.35_armhf.deb
node -v
npm -v
npm install -g node-gyp
git clone https://github.com/KhaosT/HAP-NodeJS.git
cd HAP-NodeJS
npm rebuild
node Core.js

What do you think?
BTW, thanks for helping the noob... :)

**Comment by micpura** [comment]
Follows steps above and node-gyp fails to install.  Trace/break error.  What version should I be working with?

**Comment by KhaosT** [comment]
@micpura I tried the exactly same steps with a clean Raspbian image and it worked for me.
