### ISSUE TITLE
On 3G Connection

### ISSUE THREAD

**Issue by massinegro204** [KhaosT/HomeKit-Demo#27]
One simply question .... But this work on only 3G Connection ?

**Comment by KhaosT** [comment]
@massinegro204 For HomeKit accessory to work over 3G, you will need an Apple TV in your local WiFi (to act as bridge). Both Apple TV and iOS device need to sign in with the same iCloud ID.

**Comment by massinegro204** [comment]
Thanks

**Comment by massinegro204** [comment]
i have set the iCloud address on Apple TV and on my iphone and then I have to do another something on appletv? or on iphone

**Comment by KhaosT** [comment]
@massinegro204 The "Remote Access" should be transparent. There is nothing else you need (or you can) do to get it work... If it didn't work for you, I suggest you file a bug with Apple.

**Comment by massinegro204** [comment]
maybe the whole thing and caused by the fact that I have not ios8 but ios7?

**Comment by massinegro204** [comment]
This is true or even with the io7

**Comment by KhaosT** [comment]
HomeKit only works with iOS 8.

**Comment by massinegro204** [comment]
ok thanks
