### ISSUE TITLE
error on add User

### ISSUE THREAD

**Issue by massinegro204** [KhaosT/HomeKit-Demo#28]
i try to set one users ,but if i Enter the iCloud address i have this error 

HomeKitDemo[1776:100159] Add user failed: Error Domain=HMErrorDomain Code=3 "The operation couldn’t be completed. (HMErrorDomain error 3.)"

**Comment by KhaosT** [comment]
@massinegro204 I never see Error 3 for adding user, can you post the log from device console generated by homed?

**Comment by massinegro204** [comment]
i have this error in logs
Mar  9 21:08:02 iPhone-di-Massimo identityservicesd[xx] <Warning>: [Warning] Warning, missing mailto:xxxxxxxxxxx@icloud.com in (null)
Mar  9 21:08:02 iPhone-di-Massimo homed[267] <Warning>: Failed to send message with identifier         from account: IDSAccount:        [Service: com.apple.private.alloy.willow  User: xxxxxxx@gmail.com  ID:        Type: Apple ID  Active: YES  Registration Status: Registered] with error: Error Domain=com.apple.identityservices.error Code=3 "Remote user isn't registered" UserInfo=xxxxxxxxx {NSLocalizedDescription=Remote user isn't registered, NSUnderlyingError=xxxxxxxxxx "The operation couldn‚Äôt be completed. (com.apple.ids.idssenderrordomain error 1.)"}
Mar  9 21:08:02 iPhone-di-Massimo homed[xxxx] <Warning>: Failed to send invite request due to error: Error Domain=HMErrorDomain Code=40 "The operation couldn‚Äôt be completed. (HMErrorDomain error 40.)"
Mar  9 21:08:02 iPhone-di-Massimo HomeKitDemo[622] <Warning>: Add user failed: Error Domain=HMErrorDomain Code=40 "The operation couldn‚Äôt be completed. (HMErrorDomain error 40.)"

**Comment by massinegro204** [comment]
i insert iCloud account and my my account for iCloud is gmail

**Comment by KhaosT** [comment]
@massinegro204 For some reason IdentitySerivce think the iCloud ID you are trying to invite doesn't exist. If you believe the ID is correct, please file a bug with Apple.

**Comment by wanglei827** [comment]
but i receive  "Notification not supported"
