### ISSUE TITLE
Adding accessory fails with code 66 (Operation couldn't be completed)

### ISSUE THREAD

**Issue by lucicop** [KhaosT/HomeKit-Demo#30]
Hi,

Most probably the issue is on my side, but do you have an idea why I receive those errors (in the iPhone console):

Mar 18 12:50:58 iPhone homed[2548] <Error>: Treating OSStatus -25300 (errSecItemNotFound) as Generic error
Mar 18 12:51:00 iPhone BTServer[61] <Error>: ATT        Failed to locate GATT primary service on device "8E2938FA-2EA4-36BA-4FC9-F9941CFF34B4"
Mar 18 12:51:00 iPhone homed[2548] <Error>: Treating OSStatus -25300 (errSecItemNotFound) as Generic error
Mar 18 12:52:07 iPhone homed[2548] <Error>: ### [HAP Accessory Server BTLE] Failed converting from BTLE UUID to internal: 0000FED3-0000-1000-8000-00805F9B34FB
Mar 18 12:52:07 iPhone homed[2548] <Error>: ### Unable to parse BTLE service
Mar 18 12:52:07 iPhone homed[2548] <Error>: [HAP Service Discovery] Failed HAP service discovery on accessory server <HAPAccessoryServerBTLE: 0x145e488f0>
	Peripheral: <CBPeripheral: 0x145d54bf0, identifier = 8E2938FA-2EA4-36BA-4FC9-F9941CFF34B4, name = HAP Light, state = connected>
	State: Performing HAP Service Discovery
	 with error: Error Domain=HMErrorDomain Code=66 "The operation couldn’t be completed. (HMErrorDomain error 66.)"
Mar 18 12:52:07 iPhone homed[2548] <Error>: ### [HAP Accessory Server BTLE] Failed converting from BTLE UUID to internal: 0000FED2-0000-1000-8000-00805F9B34FB

Regards,
Lucian

**Comment by lucicop** [comment]
Seems to be related to the way GATT database is constructed. I am using BlueGiga module, and they have a compiler to do that from XML. Also, iOS characteristics caching seemed to have something to do with that. I still get the "failed to locate primary GATT service", although in theory all services are marked as primary. Do you have an idea why ?

**Comment by KhaosT** [comment]
@lucicop the "failed to locate primary GATT service" is a known issue with CoreBluetooth on iOS but that shouldn't affect HomeKit BTLE Accessory when you see that. What's the version of iOS are you testing with and does HomeKit Accessory Simulator's BTLE accessory works for you?

**Comment by lucicop** [comment]
Thank you for the reply. I am using iOS 8.2, and the simulated accessories work.

**Comment by KhaosT** [comment]
@lucicop OK, is that possible for you to post the gatt.xml the part that defines the service "FED3"?

**Comment by lucicop** [comment]
I don't think I am supposed to publish it here, since the characteristics IDs are from the Apple MFi documentation... I managed to fix the problem by rearranging gatt.xml, the problem was caused by the GATT compiler from Bluegiga.

**Comment by KhaosT** [comment]
Glad to know you fixed the issue :)
