### ISSUE TITLE
Control custom characteristics

### ISSUE THREAD

**Issue by wzoet** [KhaosT/HomeKit-Demo#31]
Hi,

This might be a long shot, and I respect that you want to support all normal characteristics first, but who knows.

I use your app to support development of my homekit bridge. It works very nice!
One of my features requires the use of a custommade "Execute" characteristic, similar to the identify-characteristic. 

This bridge therefore has a custommade service with, among others, the "execute"-characteristic. The custom service is showing up ok and all characteristics are shown in your app. Unfortunately, the (boolean, write-only) characteristic is not written to when clicked.

In your code, I see that you check the metadata of a characteristic. For booleans, the first check you do is whether the value of the characteristic is not nil. Could you extend that code, so that for a write-only characteristic, it works like identify, and just writes true? A write-only characteristic will never have a value.

Thanks in advance

**Comment by KhaosT** [comment]
@wzoet fixed with 59b3979dd182dd7d1f951e7172ed1081b985218b
