### ISSUE TITLE
HAP device not showing in scanning results

### ISSUE THREAD

**Issue by lucicop** [KhaosT/HomeKit-Demo#32]
It used to work, then I took a pause of about two weeks. Now, when I try to find the device it doesn't appear in the list, although the HAT simulator displays it. I am using the latest HomeKitDemo version. Any ideas please ?

**Comment by lucicop** [comment]
Also, I tried resetting the HomeKit database on the phone multiple times.

**Comment by KhaosT** [comment]
@lucicop which accessory are you trying to use with? HomeKit Accessory Simulator?

**Comment by lucicop** [comment]
No,  I forgot to mention it works with those in the simulator. It's a real device, one having lightbulb service configured.

**Comment by KhaosT** [comment]
@lucicop If it's a BLE accessory, please check the advertisement data is correct (especially the status flag). iOS 8.3 enforces the requirement for status flag, accessory with incorrect flag will be filtered out from scan result.

**Comment by lucicop** [comment]
Yes, it's a BLE accessory. So that might be the reason it works in HAT, but not in iOS?

**Comment by KhaosT** [comment]
@lucicop I don't know if HAT has been updated accordingly with the changes in iOS 8.3, that might be the case. For accessory to be discoverable, the make sure the flag is set to 0x01

**Comment by lucicop** [comment]
I'll try this right away, thanks for pointing it out !

**Comment by lucicop** [comment]
Yep, now it works ! Thank you so much !

**Comment by KhaosT** [comment]
@lucicop :) Remember to update the accessory with latest MFi spec changes :)

**Comment by lucicop** [comment]
Yeah, I kind of missed the status flag :)
