### ISSUE TITLE
Garage Opener on WatchExtension?

### ISSUE THREAD

**Issue by legotheboss** [KhaosT/HomeKit-Demo#33]
Is there any plan to add the GarageOpener system to the WatchExtension?

**Comment by KhaosT** [comment]
@legotheboss It's on my plan but right now I'm just too busy to add that ... Feel free to submit a pull request if you did that :)

**Comment by KhaosT** [comment]
Commit 767b7fba48b5f323776c98b6d500431028601cf0 added support for Garage Door Opener.
