### ISSUE TITLE
EventTrigger

### ISSUE THREAD

**Issue by nachkar** [KhaosT/HomeKit-Demo#36]
How can I implement an event Trigger that will be available in the iOS 9 SDK ?? instead of adding a timer to turn on a light, I need to turn it on if the motion sensor detects any movements.

Some help plz

**Comment by KhaosT** [comment]
Please refer to Apple's official sample app [HMCatalog](https://developer.apple.com/library/prerelease/ios/samplecode/HomeKitCatalog/Introduction/Intro.html#//apple_ref/doc/uid/TP40015048) for how to create event triggers.

**Comment by incipio-srinu** [comment]
Hi thank you for the wonderful demo app. I have an issue with the HMEventTrigger. I have two events HMLocationEvent and HMCharacteristicEvent. While creating the HMEventTrigger I have used the below code , then it is applying the OR condition between the events . Could you please tell me how apply the AND condition? Thanks in advance.

```
NSMutableArray *arr = [[NSMutableArray alloc] initWithCapacity:0];
[arr addObject:event1];
[arr addObject:event2];

        tr2 = [[HMEventTrigger alloc] initWithName:conditionName.text events:arr predicate:nil];

```
I tried to add the predicate but issue is I am unable to prepare the predicate for HMLocationEvent. For HMCharacteristicEvent I have used the below code.

```
            HMCharacteristicWriteAction *chWr = [allCharacteristicsArr objectAtIndex:0];
            
            NSPredicate *pred =  [HMEventTrigger predicateForEvaluatingTriggerWithCharacteristic:chWr.characteristic relatedBy:NSEqualToPredicateOperatorType toValue:chWr.targetValue];

```
