### ISSUE TITLE
update to swift 2.0?

### ISSUE THREAD

**Issue by luxus** [KhaosT/HomeKit-Demo#37]
do you plan to update this thing to swift 2.0 ? perhaps adding events? :)

**Comment by KhaosT** [comment]
@luxus given that Apple released their sample app [HMCatalog](https://developer.apple.com/library/prerelease/ios/samplecode/HomeKitCatalog/Introduction/Intro.html#//apple_ref/doc/uid/TP40015048), the plan to update the app to support new enhancements in iOS 9 isn't on the top of the list.
