### ISSUE TITLE
adding user throws HMErrorCodeUserIDNotEmailAddress            

### ISSUE THREAD

**Issue by 128keaton** [KhaosT/HomeKit-Demo#4]
Cant think of anything it might be other than some iCloud clusterfuck. Tried on both and iCloud and non-icloud enabled device.

**Comment by samiramin** [comment]
Have anyone have added user successfully? I have tried to add user with my icloud account but it returns error code 7 i.e HMErrorCodeNotificationNotSupported. 
Notification error ? i am surprised. what is this for...
I even tried to add user with Apple's HMcatalog application it gives me the same error.

**Comment by KhaosT** [comment]
@samiramin Adding user works for me. If possible, can you check the system console output on iOS device and see what log does "homed" produce when the add user fails?

**Comment by samiramin** [comment]
This is the error code i am getting.
Feb 15 15:18:47 iPod homed[515] <Warning>: Failed to send invite request due to error: Error Domain=com.apple.identityservices.error Code=7 "Could not find valid account" UserInfo=0x14639f60 {NSLocalizedDescription=Could not find valid account}
Feb 15 15:18:47 iPod Pella[508] <Warning>: Error Code : 7

**Comment by KhaosT** [comment]
@samiramin For this situation, please make sure you enabled iCloud Keychain Syncing on both device and maybe try to update your iOS to 8.1.3. If it's still not working, please file a bug at bugreport.apple.com .

**Comment by samiramin** [comment]
I have already filed a bug  at Apple bug reporter, and i am signed into two different devices one is iOS 8.1.3 and second is 8.1 keychain is enabled in both.
I am disappointed with apple as they doesn't provide proper document for this.

**Comment by wanglei827** [comment]
@samiramin  do you resolve this question?
